language: python
python:
  - "2.7"
  - "3.4"
  - "pypy"
install:
  - pip install -e . --use-mirrors
  - pip install Django --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install pytest --use-mirrors
  - pip install pytz --use-mirrors
script:
  - pep8 --repeat --show-source --exclude=.venv,.tox,dist,doc,build,*.egg,*.yml .
